version: "3.7"
services:
    web:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8999:80"
        volumes:
            - .:/var/www
        extra_hosts:
          - "host.docker.internal:${EN0_INET_IP}"