version: "3.7"
services:
    slim_skeleton:
        build:
            context: .
            dockerfile: ./Dockerfile
        ports:
            - "8000:80"
        volumes:
            - .:/var/www
        extra_hosts:
            - "host.docker.internal:${EN0_INET_IP}"